- start.py
I am opening this Pull Request because I want to constantly improve the script as I see problems. Two problems are currently fixed.
One of them was the very slow collection of Proxys and the other was a problem known as "UnboundLocalError: local variable referenced before assignment" that was hurting the performance of the program.
> Script Upgrades

- start.py
amplification methods (with input files) didn't work in debug mode
> fix debug mode for amplification methods

- start.py
> Accidental concatenation of `APACHE` and `BOT` in start.py fix

- README.md
- requirements.txt
- start.py
https://github.com/SecureAuthCorp/impacket/issues/1266#issuecomment-1047785343
> Update requirements.txt, because of Windows error, add bombardier

- start.py
Added Random HTTP Version For L7
Fixed debug mode L4
Fixed help text
> Added Random HTTPv For L7

- start.py
It is no longer necessary as utf-8 is the default.
> Remove unnecessary encoding declaration

- .github/BOMBARDIER.md
- README.md
If you want to change the command, please change the comment above.
> Forked for safety, fixed link, add instalation link, fix command

- files/useragent.txt
> Added More Useragents

- start.py
Fixed some f-string format 
Fixed Legacy code format
Modified to f-string formatting base
> Fixed Legacy code formatting To f-string format

- start.py
> Revert "Fixed Legacy code formatting To f-string format"

- start.py
Fixed Formatting 
Removed (object) from class Counter(object) Line 103
cause a class is inherited from object by default
> Fixed Formatting

- start.py
Simplify calling this module from the outside by wrapping code into function.
I am maintaining a wrapper script and it would be helpful to be able to run MHDDoS as a function. I've kept the changes to minimal, hope you'll accept this PR.
> wrap all code into function

- start.py
> Revert "wrap all code into function"

- start.py
There's a typo where it says form but it's supposed to be from.
> Fixed form to from in line 981 and 999

- start.py
https://github.com/MHProDev/MHDDoS/pull/290 
@gidiyan
> Added host and port to logger

- config.json
i checked all the sources checking should go faster with better results!
> Remove dead/dupelicate sources + add sources

- start.py
- Port starts with `ndd /dev/tcp tcp_smallest_anon_port`
- Random port instead of fixed port each time
> Make SYN more realistic

- start.py
just adds more tor2web gateways to the list
> Add more tor2web gateways

- start.py
https://pypi.org/project/codespell
> Fix typos discovered by codespell

- README.md
- requirements.txt
I have added inside the readme.md some One-Line instructions for newly deployed debian/ubuntu servers and I have updated again the dependencies inside the requirements.txt
> New installing method in readme.md & update of python modules

- start.py
PPS was broken after last update, fixed it and removed redundant code
> Fixed PPS 
